version: '2'
services:

  # Alpine and Fpm based images
  nginx:
    image: nginx:alpine
    ports:
      - "7070:80"
    volumes:
      - './conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    links:
      - "wordpress"
    volumes_from:
      - "wordpress:ro"
    environment:
      NGINX_PORT: "8080"

  wordpress_fpm_db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${WORDPRESS_MYSQL_USER}
      MYSQL_PASSWORD: ${WORDPRESS_MYSQL_PASSWORD}

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    image: ellakcy/wordpressswithplugins:alpine-fpm
    links:
      - wordpress_fpm_db
    depends_on:
      - wordpress_fpm_db
    environment:
        WORDPRESS_DB_HOST: wordpress_fpm_db
        WORDPRESS_DB_USER: ${WORDPRESS_MYSQL_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_MYSQL_PASSWORD}
        WORDPRESS_ADMIN_USERNAME: ${WORDPRESS_ADMIN_USER}
        WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
        WORDPRESS_URL: ${WORDPRESS_URL}

# Apache Build

  wordpress_apache_db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${WORDPRESS_MYSQL_USER}
      MYSQL_PASSWORD: ${WORDPRESS_MYSQL_PASSWORD}

  wordpress_apache:
    build:
      context: .
      dockerfile: Dockerfile_apache
    image: ellakcy/wordpressswithplugins:apache
    links:
      - wordpress_apache_db
    depends_on:
      - wordpress_apache_db
    ports:
      - "7071:80"
    environment:
        WORDPRESS_DB_HOST: wordpress_apache_db
        WORDPRESS_DB_USER: ${WORDPRESS_MYSQL_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_MYSQL_PASSWORD}
        WORDPRESS_ADMIN_USERNAME: ${WORDPRESS_ADMIN_USER}
        WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
        WORDPRESS_URL: ${WORDPRESS_APACHE_URL}
